### ISSUE TITLE
Autocomplete replacement ranges are incorrect?

### ISSUE THREAD

**Issue by Ryex** [mkslanc/ace-linters#110]
As a helpful tester pointed out on my project...

https://github.com/Ryex/ic10emu/issues/3

Autocomplete replacements seems to incorrect, the last character entered before the replacement was accepted gets placed in front.

Project is live at https://ryex.github.io/ic10emu/ so you can try to replicate the issue yourself. I have the LSP messages logged in the console so I can see that the message is well formed as screenshot in the linked issue

**Comment by mkslanc** [comment]
@Ryex hey! Seems your server is providing wrong edit ranges. You could use `insertText` instead of `textEdit` so the ace client will take prefix replace calculations or provide correct insert/replace ranges. Right now prefixes are not considered.
![image](https://github.com/mkslanc/ace-linters/assets/32402726/7c452867-f3e8-45ff-a24a-d2b68ad4e636)
For example: I reproduced same your issue and in that case `range.end.column` should be +1.

**Comment by mkslanc** [comment]
[This is how ace client handles those ranges](https://github.com/ajaxorg/ace/blob/master/src/autocomplete.js#L846)

**Comment by Ryex** [comment]
Interesting. Neovim handles these edit ranges just fine so I assumed that wasn't the issue.
but editing the lsp to use a length of 1 for the edit range does indeed seem to fix the problem.
![image](https://github.com/mkslanc/ace-linters/assets/508861/5cfa8664-17d6-4db3-95bd-b89426c8c945)

And testing with Neovim shows that it still works there.
Considering I'm already maintaining a branch of the lsp to compile it to Wasm I suppose this isn't all that bad an outcome.
